const verbs = [
    "run",
    "eat",
    "read",
    "write",
    "play",
    "talk",
    "walk",
    "think",
    "study",
    "teach",
    "buy",
    "sell",
    "type",
    "speak",
    "work out",
    "walk",
    "listen to music",
    "watch tv",
    "watch tiktoks",
    "watch reels",
    "play piano",
    "play guitar",
    "play volleyball",
    "play basketball",
    "play football",
    "play soccer",
    "play violin",
    "sell things",
    "study",
    "do homework"
];
const names = [
    "Mateo",
    "Liam",
    "Santiago",
    "Noah",
    "Benjamín",
    "Lucas",
    "Elías",
    "Ethan",
    "Thiago",
    "James",
    "Gael",
    "Oliver",
    "Martín",
    "Aiden",
    "Julián",
    "Leo",
    "Samuel",
    "Dylan",
    "Nicolás",
    "Logan",
    "Sebastián",
    "Mason",
    "Tomás",
    "Ezra",
    "Bruno",
    "Jackson",
    "Emiliano",
    "Owen",
    "Andrés",
    "Levi",
    "Alexander",
    "Emmanuel",
    "Caleb",
    "Gabriel",
    "Lautaro",
    "Hunter",
    "Iván",
    "Carter",
    "Adrián",
    "Jayden",
    "Cristóbal",
    "Wyatt",
    "Maximiliano",
    "Jaxon",
    "Rodrigo",
    "Isaac",
    "Enzo",
    "David",
    "Axel",
    "Grayson",
    "Joshua",
    "Simón",
    "Asher",
    "Francisco",
    "Nolan",
    "Joaquín",
    "Colton",
    "Alan",
    "Luca",
    "Diego",
    "Roman",
    "Felipe",
    "Camilo",
    "Bentley",
    "Kevin",
    "Eli",
    "Aaron",
    "Ian",
    "Matías",
    "Zane",
    "Angel",
    "Carlos",
    "Nathan",
    "Esteban",
    "Julio",
    "Ryder",
    "Hugo",
    "Damian",
    "Brian",
    "Leonardo",
    "Jayce",
    "Damián",
    "Milo",
    "Rafael",
    "Arlo",
    "Raúl",
    "Brody",
    "Marco",
    "Gael",
    "Beckett",
    "Cristian",
    "Tobías",
    "Victor",
    "Xander",
    "Luciano",
    "Kingston",
    "Jared",
    "Thiago",
    "Ezequiel",
    "Miles",
    "Emma",
    "Sofía",
    "Isabella",
    "Valentina",
    "Olivia",
    "Camila",
    "Emilia",
    "Mia",
    "Victoria",
    "Ava",
    "Martina",
    "Amelia",
    "Catalina",
    "Luna",
    "Chloe",
    "Lucía",
    "Abigail",
    "Mariana",
    "Emily",
    "Renata",
    "Zoe",
    "Daniela",
    "Ella",
    "Julieta",
    "Madison",
    "Sara",
    "Ariana",
    "Lía",
    "Savannah",
    "Josefina",
    "Nora",
    "Florencia",
    "Layla",
    "Allison",
    "Alma",
    "Hailey",
    "Ivanna",
    "Natalie",
    "Bianca",
    "Brooklyn",
    "Agustina",
    "Grace",
    "Melina",
    "Elena",
    "Isidora",
    "Hazel",
    "Mila",
    "Clara",
    "Gabriela",
    "Naomi",
    "Miranda",
    "Gianna",
    "Violeta",
    "Aubrey",
    "Regina",
    "Zahara",
    "Kiara",
    "Penélope",
    "Aria",
    "Celeste",
    "Leah",
    "Maite",
    "Luciana",
    "Scarlett",
    "Delfina",
    "Faith",
    "Noelia",
    "Nicole",
    "Ashley",
    "Milagros",
    "Paula",
    "Riley",
    "Lola",
    "Aitana",
    "Juliana",
    "Emily",
    "Antonella",
    "Tessa",
    "Ambar",
    "Kylie",
    "Ludmila",
    "Adriana",
    "Valery",
    "Graciela",
    "Emery",
    "Samantha",
    "Alina",
    "Tamara",
    "Carmen",
    "Isla",
    "Estrella",
    "Danna",
    "Yasmin",
    "Skylar",
    "Claudia",
    "Maya",
    "Jimena",
    "Harper",
    "Karina"
];

function getRandomItem(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function getActivities() {
    let activities = [];
    for (let i = 0; i < 4; i++) {
        const verb = getRandomItem(verbs);
        const withSomeone = Math.random() < 0.25; // 25% de chance
        const activity = withSomeone ? `${verb} with ${getRandomItem(names)}` : verb;
        activities.push(activity);
    }
    return activities;
}

function generateschedule() {
    const scheduleDiv = document.getElementById("schedule");
    const today = new Date();
    
    for (let i = 0; i < 14; i++) {
        const currentDate = new Date();
        currentDate.setDate(today.getDate() + i);

        const isToday = currentDate.toDateString() === today.toDateString();
        const day = currentDate.toLocaleDateString("en-US", { weekday: 'long' });
        const date = currentDate.getDate();
        const month = currentDate.toLocaleDateString("en-US", { month: 'long' });

        const activities = getActivities();
        const dayHTML = `
            <div class="day-card ${isToday ? 'today' : ''}">
                <h3>${day} ${date} ${month}</h3>
                <ul>
                    ${activities.map(act => `<li>${act}</li>`).join("")}
                </ul>
            </div>
        `;
        scheduleDiv.innerHTML += dayHTML;
    }
}

generateschedule();
