const salutations = [
    "Hi!",
    "Hello",
    "Good morning",
    "Morning!",
    "Good afternoon",
    "Good evening",
    "Hi, good morning",
    "Hi, good afternoon",
    "Hi, good evening",
    "Hello, good morning",
    "Hello, good afternoon",
    "Hello, good evening"
];

const introducings = [
    "I'm",
    "I am",
    "my name is"
];

const names = [
    "Mateo",
    "Liam",
    "Santiago",
    "Noah",
    "Benjamín",
    "Lucas",
    "Elías",
    "Ethan",
    "Thiago",
    "James",
    "Gael",
    "Oliver",
    "Martín",
    "Aiden",
    "Julián",
    "Leo",
    "Samuel",
    "Dylan",
    "Nicolás",
    "Logan",
    "Sebastián",
    "Mason",
    "Tomás",
    "Ezra",
    "Bruno",
    "Jackson",
    "Emiliano",
    "Owen",
    "Andrés",
    "Levi",
    "Alexander",
    "Emmanuel",
    "Caleb",
    "Gabriel",
    "Lautaro",
    "Hunter",
    "Iván",
    "Carter",
    "Adrián",
    "Jayden",
    "Cristóbal",
    "Wyatt",
    "Maximiliano",
    "Jaxon",
    "Rodrigo",
    "Isaac",
    "Enzo",
    "David",
    "Axel",
    "Grayson",
    "Joshua",
    "Simón",
    "Asher",
    "Francisco",
    "Nolan",
    "Joaquín",
    "Colton",
    "Alan",
    "Luca",
    "Diego",
    "Roman",
    "Felipe",
    "Camilo",
    "Bentley",
    "Kevin",
    "Eli",
    "Aaron",
    "Ian",
    "Matías",
    "Zane",
    "Angel",
    "Carlos",
    "Nathan",
    "Esteban",
    "Julio",
    "Ryder",
    "Hugo",
    "Damian",
    "Brian",
    "Leonardo",
    "Jayce",
    "Damián",
    "Milo",
    "Rafael",
    "Arlo",
    "Raúl",
    "Brody",
    "Marco",
    "Gael",
    "Beckett",
    "Cristian",
    "Tobías",
    "Victor",
    "Xander",
    "Luciano",
    "Kingston",
    "Jared",
    "Thiago",
    "Ezequiel",
    "Miles",
    "Emma",
    "Sofía",
    "Isabella",
    "Valentina",
    "Olivia",
    "Camila",
    "Emilia",
    "Mia",
    "Victoria",
    "Ava",
    "Martina",
    "Amelia",
    "Catalina",
    "Luna",
    "Chloe",
    "Lucía",
    "Abigail",
    "Mariana",
    "Emily",
    "Renata",
    "Zoe",
    "Daniela",
    "Ella",
    "Julieta",
    "Madison",
    "Sara",
    "Ariana",
    "Lía",
    "Savannah",
    "Josefina",
    "Nora",
    "Florencia",
    "Layla",
    "Allison",
    "Alma",
    "Hailey",
    "Ivanna",
    "Natalie",
    "Bianca",
    "Brooklyn",
    "Agustina",
    "Grace",
    "Melina",
    "Elena",
    "Isidora",
    "Hazel",
    "Mila",
    "Clara",
    "Gabriela",
    "Naomi",
    "Miranda",
    "Gianna",
    "Violeta",
    "Aubrey",
    "Regina",
    "Zahara",
    "Kiara",
    "Penélope",
    "Aria",
    "Celeste",
    "Leah",
    "Maite",
    "Luciana",
    "Scarlett",
    "Delfina",
    "Faith",
    "Noelia",
    "Nicole",
    "Ashley",
    "Milagros",
    "Paula",
    "Riley",
    "Lola",
    "Aitana",
    "Juliana",
    "Emily",
    "Antonella",
    "Tessa",
    "Ambar",
    "Kylie",
    "Ludmila",
    "Adriana",
    "Valery",
    "Graciela",
    "Emery",
    "Samantha",
    "Alina",
    "Tamara",
    "Carmen",
    "Isla",
    "Estrella",
    "Danna",
    "Yasmin",
    "Skylar",
    "Claudia",
    "Maya",
    "Jimena",
    "Harper",
    "Karina"
];

const last_names = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "García",
    "Martínez",
    "Rodríguez",
    "González",
    "Hernández",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "López",
    "Pérez",
    "Sánchez",
    "Ramírez",
    "Cruz",
    "Moore",
    "Hall",
    "Young",
    "Allen",
    "King",
    "Torres",
    "Rivera",
    "Castillo",
    "Morales",
    "Ortiz",
    "Harris",
    "Lewis",
    "Walker",
    "Robinson",
    "Scott",
    "Vargas",
    "Gómez",
    "Mendoza",
    "Chávez",
    "Reyes",
    "Green",
    "Clark",
    "Adams",
    "Baker",
    "Mitchell",
    "Jiménez",
    "Silva",
    "Fuentes",
    "Guerrero",
    "Ramos"
];

const spellings = [
    "You write it like",
    "The way you spell it is",
    "The way you spell the name is",
    "The way to spell the name is",
    "You spell it like",
    "It spells",
    "The spelling is"
];

function numberGenerator(digits) {
    let number = "";
    for (let i = 0; i < digits; i++) {
        let randomDigit = Math.floor(Math.random() * 10); // 0 a 9
        number += randomDigit;
    }
    return number; // O solo `return number` si prefieres un string
};
function getRandomElement(array) {
  return array[Math.floor(Math.random() * array.length)];
};

const fullName = [
    getRandomElement(names),
    getRandomElement(last_names)
].join(" ");

const firstLine = [
    getRandomElement(salutations),
    getRandomElement(introducings),
    fullName
].join(" ");

const secondLine = [
    getRandomElement(spellings),
    fullName.toUpperCase()
].join(" ");

const fourthLine = [
    "+",
    numberGenerator(2),
    numberGenerator(1),
    numberGenerator(4),
    numberGenerator(6),
].join(" ");

document.getElementById("1st-line").innerText = firstLine;
document.getElementById("2nd-line").innerText = secondLine;
document.getElementById("4th-line").innerText = fourthLine;